rulesets:
  - name: n64
    extract: true
    move: ./organized/n64
    rename: '{name}.z64'
  - name: psx
    extract: true
    move: ./organized/psx
    rename: '{name}.bin'
  - name: gba
    extract: true
    move: ./organized/gba
    rename: '{name}.gba'
